services:
    db:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: office_pong
        ports:
            - '5432:5432'
        volumes:
            - office_pong_db_data:/var/lib/postgresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    office_pong_db_data:
