name: Job summary
description: Creates a job summary for the workflow run
inputs:
    image-ref:
        description: 'The reference to the Docker image'
        required: true
    new-version:
        description: 'The new version (for production deployments)'
        required: false
    new-tag:
        description: 'The new git tag (for production deployments)'
        required: false
    previous-tag:
        description: 'The previous git tag (for production deployments)'
        required: false
    increment-type:
        description: 'The version increment type (for production deployments)'
        required: false
    pr-url:
        description: 'URL of the pull request associated with this deployment'
        required: false
    environment:
        description: 'The deployment environment'
        required: false

runs:
    using: 'composite'
    steps:
        - name: Write job summary
          shell: bash
          run: |
              echo "# Build and deploy successful 🎉" >> $GITHUB_STEP_SUMMARY
              {
                echo "➡️ **[Pull request in app-configrepo-fremtind](${{ inputs.pr-url }})**"
                echo "## Git info 👨‍💻"
                echo "- **Commit**: ${{ github.sha }}"
                echo "- **Run number**: ${{ github.run_number }}"
                echo "- **Run attempt**: ${{ github.run_attempt }}"
                echo "- **By**: ${{ github.actor }}"
                echo
                echo "## Docker / AWS info 🐳"
                echo "- **Image reference**: ${{ inputs.image-ref }}"
                echo "- **Environment**: ${{ inputs.environment || 'test' }}"
                
                # Add version information if this is a production deployment
                if [ -n "${{ inputs.new-version }}" ]; then
                  echo
                  echo "## Release info 🚀"
                  echo "- **New Version**: [${{ inputs.new-tag }}](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ inputs.new-tag }})"
                  echo "- **Previous Version**: ${{ inputs.previous-tag }}"
                  echo "- **Version Increment**: ${{ inputs.increment-type }}"
                  echo "- **Release Page**: [${{ inputs.new-tag }} Release](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ inputs.new-tag }})"
                  echo "- **Compare Changes**: [View Changes](${{ github.server_url }}/${{ github.repository }}/compare/${{ inputs.previous-tag }}...${{ inputs.new-tag }})"
                fi
              } >> $GITHUB_STEP_SUMMARY
