// This file is auto-generated by @hey-api/openapi-ts

/**
 * System message client types
 */
export type ClientType = 'SAM' | 'SKS' | 'KUNDESOK_BM';

/**
 * Distribution group types
 */
export type DistGroupType = 'FRE' | 'SB1' | 'DNB' | 'EIK' | 'FAN' | 'MOR';

/**
 * System message with publication settings and target audience
 */
export type SystemMessageDto = {
    /**
     * Unique identifier
     */
    id?: string;
    title?: string;
    /**
     * Message content
     */
    message: string;
    /**
     * When the message should start being displayed
     */
    publishFrom: string;
    /**
     * When the message should stop being displayed
     */
    publishTo: string;
    /**
     * User who created the message
     */
    createdBy?: string;
    /**
     * Type of message (e.g. WARNING, INFO, ERROR)
     */
    type: 'INFO' | 'WARNING' | 'ERROR';
    /**
     * Clients that should receive this message
     */
    clients?: Array<ClientType>;
    /**
     * Distribution groups that should receive this message
     */
    distGroups?: Array<DistGroupType>;
    /**
     * Whether users can dismiss the message
     */
    isDismissible: boolean;
    /**
     * Whether the message is disabled regardless of publish dates
     */
    isDisabled: boolean;
    /**
     * Whether the message is currently active (calculated)
     */
    isActive: boolean;
    /**
     * When the message was created
     */
    createdAt?: string;
    /**
     * When the message was last modified
     */
    lastModified?: string;
};

export type UserDto = {
    id: string;
    name?: string;
};

export type DeleteMessageData = {
    body?: never;
    path: {
        /**
         * ID of the message to delete
         */
        id: string;
    };
    query?: never;
    url: '/api/system-messages/{id}';
};

export type DeleteMessageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetMessageByIdData = {
    body?: never;
    path: {
        /**
         * ID of the message to retrieve
         */
        id: string;
    };
    query?: never;
    url: '/api/system-messages/{id}';
};

export type GetMessageByIdResponses = {
    /**
     * OK
     */
    200: SystemMessageDto;
};

export type GetMessageByIdResponse = GetMessageByIdResponses[keyof GetMessageByIdResponses];

export type UpdateMessageData = {
    body: SystemMessageDto;
    path: {
        /**
         * ID of the message to update
         */
        id: string;
    };
    query?: never;
    url: '/api/system-messages/{id}';
};

export type UpdateMessageResponses = {
    /**
     * OK
     */
    200: SystemMessageDto;
};

export type UpdateMessageResponse = UpdateMessageResponses[keyof UpdateMessageResponses];

export type GetMessagesWithFiltersData = {
    body?: never;
    path?: never;
    query?: {
        clientName?: string;
        active?: boolean;
        inactive?: boolean;
        disabled?: boolean;
    };
    url: '/api/system-messages';
};

export type GetMessagesWithFiltersResponses = {
    /**
     * OK
     */
    200: Array<SystemMessageDto>;
};

export type GetMessagesWithFiltersResponse = GetMessagesWithFiltersResponses[keyof GetMessagesWithFiltersResponses];

export type PostMessageData = {
    body: SystemMessageDto;
    path?: never;
    query?: never;
    url: '/api/system-messages';
};

export type PostMessageResponses = {
    /**
     * OK
     */
    200: SystemMessageDto;
};

export type PostMessageResponse = PostMessageResponses[keyof PostMessageResponses];

export type EnableMessageData = {
    body?: never;
    path: {
        /**
         * ID of the message to enable
         */
        id: string;
    };
    query?: never;
    url: '/api/system-messages/{id}/enable';
};

export type EnableMessageResponses = {
    /**
     * OK
     */
    200: SystemMessageDto;
};

export type EnableMessageResponse = EnableMessageResponses[keyof EnableMessageResponses];

export type DisableMessageData = {
    body?: never;
    path: {
        /**
         * ID of the message to disable
         */
        id: string;
    };
    query?: never;
    url: '/api/system-messages/{id}/disable';
};

export type DisableMessageResponses = {
    /**
     * OK
     */
    200: SystemMessageDto;
};

export type DisableMessageResponse = DisableMessageResponses[keyof DisableMessageResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/user';
};

export type GetUserResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type ClientOptions = {
    baseUrl: 'https://rk-admin.intern.app.devaws.fremtind.no' | (string & {});
};