/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NyKampRouteImport } from './routes/ny-kamp'
import { Route as LedertavleRouteImport } from './routes/ledertavle'
import { Route as KamperRouteImport } from './routes/kamper'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilIdRouteImport } from './routes/profil.$id'
import { Route as ApiHealthRouteImport } from './routes/api.health'

const NyKampRoute = NyKampRouteImport.update({
  id: '/ny-kamp',
  path: '/ny-kamp',
  getParentRoute: () => rootRouteImport,
} as any)
const LedertavleRoute = LedertavleRouteImport.update({
  id: '/ledertavle',
  path: '/ledertavle',
  getParentRoute: () => rootRouteImport,
} as any)
const KamperRoute = KamperRouteImport.update({
  id: '/kamper',
  path: '/kamper',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIdRoute = ProfilIdRouteImport.update({
  id: '/profil/$id',
  path: '/profil/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kamper': typeof KamperRoute
  '/ledertavle': typeof LedertavleRoute
  '/ny-kamp': typeof NyKampRoute
  '/api/health': typeof ApiHealthRoute
  '/profil/$id': typeof ProfilIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kamper': typeof KamperRoute
  '/ledertavle': typeof LedertavleRoute
  '/ny-kamp': typeof NyKampRoute
  '/api/health': typeof ApiHealthRoute
  '/profil/$id': typeof ProfilIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kamper': typeof KamperRoute
  '/ledertavle': typeof LedertavleRoute
  '/ny-kamp': typeof NyKampRoute
  '/api/health': typeof ApiHealthRoute
  '/profil/$id': typeof ProfilIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kamper'
    | '/ledertavle'
    | '/ny-kamp'
    | '/api/health'
    | '/profil/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kamper'
    | '/ledertavle'
    | '/ny-kamp'
    | '/api/health'
    | '/profil/$id'
  id:
    | '__root__'
    | '/'
    | '/kamper'
    | '/ledertavle'
    | '/ny-kamp'
    | '/api/health'
    | '/profil/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KamperRoute: typeof KamperRoute
  LedertavleRoute: typeof LedertavleRoute
  NyKampRoute: typeof NyKampRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ProfilIdRoute: typeof ProfilIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ny-kamp': {
      id: '/ny-kamp'
      path: '/ny-kamp'
      fullPath: '/ny-kamp'
      preLoaderRoute: typeof NyKampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledertavle': {
      id: '/ledertavle'
      path: '/ledertavle'
      fullPath: '/ledertavle'
      preLoaderRoute: typeof LedertavleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamper': {
      id: '/kamper'
      path: '/kamper'
      fullPath: '/kamper'
      preLoaderRoute: typeof KamperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/$id': {
      id: '/profil/$id'
      path: '/profil/$id'
      fullPath: '/profil/$id'
      preLoaderRoute: typeof ProfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KamperRoute: KamperRoute,
  LedertavleRoute: LedertavleRoute,
  NyKampRoute: NyKampRoute,
  ApiHealthRoute: ApiHealthRoute,
  ProfilIdRoute: ProfilIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
