name: Release afterparty 🎉

on:
    push:
        branches:
            - main

permissions:
    contents: write
    id-token: write

jobs:
    sync:
        runs-on: [self-hosted, fremtind-default]
        permissions:
            id-token: write
        if: github.event_name == 'push'
        steps:
            - name: Authenticate with chore-bot
              uses: fremtind/action-chorebot-auth@v2
              id: token

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ steps.token.outputs.token }}

            - name: Sync develop with main
              uses: ./.github/actions/sync-branch
              with:
                source-branch: main
                target-branch: develop
                auth-token: ${{ steps.token.outputs.token }}
